version: 1.0.{build}
environment:
  version: 1.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore .\HighchartsExportClient\HighchartsExportClient.sln
build:
  publish_nuget: true  
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: lQfVnAoVblKur4VaMPXgca2Ml/Q08P3Q1VhgvnNS1Owk3immWVWbJIsZL+YNo2sB
  artifact: /.*\.nupkg/